version: 1.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
- SET
- 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
- 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  matrix:
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 21
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 21-x64
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 23
  - PUPPET_GEM_VERSION: ~> 4.0
    RUBY_VER: 23-x64
  - PUPPET_GEM_VERSION: 4.2.3
    RUBY_VER: 21-x64
matrix:
  fast_finish: true
install:
- SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
- bundle install --jobs 4 --retry 2 --without system_tests
- type Gemfile.lock
build: off
test_script:
- bundle exec puppet -V
- ruby -v
- bundle exec rake spec SPEC_OPTS='--format documentation'
notifications:
- provider: Email
  to:
  - nobody@nowhere.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
